ALTER TABLE "AttrColor"
ADD COLUMN IF NOT EXISTS "nameKo" TEXT,
ADD COLUMN IF NOT EXISTS "nameEn" TEXT;

ALTER TABLE "AttrCategory"
ADD COLUMN IF NOT EXISTS "nameKo" TEXT,
ADD COLUMN IF NOT EXISTS "nameEn" TEXT;

ALTER TABLE "AttrProcess"
ADD COLUMN IF NOT EXISTS "nameKo" TEXT,
ADD COLUMN IF NOT EXISTS "nameEn" TEXT;
