export const ASSIGNMENT_CT_STATUS_KEYS = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  AGREED: 'AGREED',
  REJECTED: 'REJECTED',
};

export const ASSIGNMENT_CT_STATUS_LABEL_KEYS = {
  [ASSIGNMENT_CT_STATUS_KEYS.PENDING]: 'assignmentStatus.pending',
  [ASSIGNMENT_CT_STATUS_KEYS.SENT]: 'assignmentStatus.sent',
  [ASSIGNMENT_CT_STATUS_KEYS.AGREED]: 'assignmentStatus.agreed',
  [ASSIGNMENT_CT_STATUS_KEYS.REJECTED]: 'assignmentStatus.rejected',
};

export const ASSIGNMENT_CT_STATUS_DEFAULT_LABELS = {
  [ASSIGNMENT_CT_STATUS_KEYS.PENDING]: '\uB300\uAE30',
  [ASSIGNMENT_CT_STATUS_KEYS.SENT]: '\uC81C\uC548',
  [ASSIGNMENT_CT_STATUS_KEYS.AGREED]: '\uD655\uC815',
  [ASSIGNMENT_CT_STATUS_KEYS.REJECTED]: '\uC694\uCCAD',
};

export const ASSIGNMENT_CT_STATUS_OPTIONS = [
  {
    value: ASSIGNMENT_CT_STATUS_KEYS.PENDING,
    labelKey: ASSIGNMENT_CT_STATUS_LABEL_KEYS[ASSIGNMENT_CT_STATUS_KEYS.PENDING],
    label: ASSIGNMENT_CT_STATUS_DEFAULT_LABELS[ASSIGNMENT_CT_STATUS_KEYS.PENDING],
  },
  {
    value: ASSIGNMENT_CT_STATUS_KEYS.SENT,
    labelKey: ASSIGNMENT_CT_STATUS_LABEL_KEYS[ASSIGNMENT_CT_STATUS_KEYS.SENT],
    label: ASSIGNMENT_CT_STATUS_DEFAULT_LABELS[ASSIGNMENT_CT_STATUS_KEYS.SENT],
  },
  {
    value: ASSIGNMENT_CT_STATUS_KEYS.AGREED,
    labelKey: ASSIGNMENT_CT_STATUS_LABEL_KEYS[ASSIGNMENT_CT_STATUS_KEYS.AGREED],
    label: ASSIGNMENT_CT_STATUS_DEFAULT_LABELS[ASSIGNMENT_CT_STATUS_KEYS.AGREED],
  },
  {
    value: ASSIGNMENT_CT_STATUS_KEYS.REJECTED,
    labelKey: ASSIGNMENT_CT_STATUS_LABEL_KEYS[ASSIGNMENT_CT_STATUS_KEYS.REJECTED],
    label: ASSIGNMENT_CT_STATUS_DEFAULT_LABELS[ASSIGNMENT_CT_STATUS_KEYS.REJECTED],
  },
];

export const ASSIGNMENT_CT_STATUS_SORT_ORDER = {
  [ASSIGNMENT_CT_STATUS_KEYS.REJECTED]: 0,
  [ASSIGNMENT_CT_STATUS_KEYS.SENT]: 1,
  [ASSIGNMENT_CT_STATUS_KEYS.PENDING]: 2,
  [ASSIGNMENT_CT_STATUS_KEYS.AGREED]: 3,
};

const ASSIGNMENT_CT_STATUS_LOCKED_VALUES = new Set([
  ASSIGNMENT_CT_STATUS_KEYS.SENT,
  ASSIGNMENT_CT_STATUS_KEYS.AGREED,
]);

export const normalizeAssignmentCtStatus = (value) => {
  const upper = String(value || '').trim().toUpperCase();
  if (upper === ASSIGNMENT_CT_STATUS_KEYS.SENT) return ASSIGNMENT_CT_STATUS_KEYS.SENT;
  if (upper === ASSIGNMENT_CT_STATUS_KEYS.AGREED) return ASSIGNMENT_CT_STATUS_KEYS.AGREED;
  if (upper === ASSIGNMENT_CT_STATUS_KEYS.REJECTED) return ASSIGNMENT_CT_STATUS_KEYS.REJECTED;
  return ASSIGNMENT_CT_STATUS_KEYS.PENDING;
};

export const getAssignmentCtStatusLabel = (value, fallback = '-') => {
  const normalized = normalizeAssignmentCtStatus(value);
  return ASSIGNMENT_CT_STATUS_DEFAULT_LABELS[normalized] || fallback;
};

export const isAssignmentCtStatusLocked = (value) =>
  ASSIGNMENT_CT_STATUS_LOCKED_VALUES.has(normalizeAssignmentCtStatus(value));
