import React, { useState } from 'react';
import { Alert, Box, Chip, FormControl, InputLabel, LinearProgress, MenuItem, Paper, Select, Stack, Tab, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Tabs, TextField, Typography } from '@mui/material';
import AppPageContainer from '../../components/AppPageContainer';
import { useLanguage } from '../../context/LanguageContext';

const TEXT = {
  ko: { title:'수익 분석', monthly:'월별 손익', orders:'주문별 손익', adjust:'전망 조정', demo:'화면 구성을 확인하기 위한 예시 데이터입니다. 실제 계산과 저장 기능은 아직 연결되지 않았습니다.', month:'분석 월', factory:'공장', all:'전체 공장', hybrid:'실적 + 전망', actual:'확정', forecast:'예상', revenue:'매출', purchase:'매입·직접비', cost:'생산 원가', profit:'수익', margin:'수익률', current:'현재까지 실적', remaining:'남은 예상', monthEnd:'월말 전망', compared:'예가 대비', composition:'월말 손익 구성', order:'주문번호', customer:'고객', style:'스타일', progress:'진행률', status:'상태', completed:'생산 완료', producing:'생산 중', review:'검토 필요', adjustment:'남은 배정 일정 조정', adjustmentHint:'배정 기간을 바꾸면 인건비·고정비와 월말 수익 전망이 다시 계산되는 화면입니다.', factoryUnit:'공장', quantity:'수량', start:'시작일', end:'종료일', impact:'전망 영향', delayed:'다음 달 이월', within:'이번 달 완료' },
  en: { title:'Profit Analysis', monthly:'Monthly P&L', orders:'Order P&L', adjust:'Forecast Adjustment', demo:'This is sample data for reviewing the UI. Calculation and save functions are not connected yet.', month:'Analysis month', factory:'Factory', all:'All factories', hybrid:'Actual + Forecast', actual:'Actual', forecast:'Forecast', revenue:'Revenue', purchase:'Purchases & direct costs', cost:'Production cost', profit:'Profit', margin:'Margin', current:'Actual to date', remaining:'Remaining forecast', monthEnd:'Month-end forecast', compared:'vs. estimate', composition:'Month-end P&L composition', order:'Order', customer:'Customer', style:'Style', progress:'Progress', status:'Status', completed:'Completed', producing:'In production', review:'Review required', adjustment:'Adjust remaining assignment schedule', adjustmentHint:'Changing assignment dates will recalculate labor, fixed costs, and the month-end profit forecast.', factoryUnit:'Factory', quantity:'Quantity', start:'Start', end:'End', impact:'Forecast impact', delayed:'Carried to next month', within:'Completes this month' },
  vi: { title:'Phân tích lợi nhuận', monthly:'Lãi lỗ theo tháng', orders:'Lãi lỗ theo đơn hàng', adjust:'Điều chỉnh dự báo', demo:'Đây là dữ liệu mẫu để kiểm tra giao diện. Chức năng tính toán và lưu chưa được kết nối.', month:'Tháng phân tích', factory:'Nhà máy', all:'Tất cả nhà máy', hybrid:'Thực tế + Dự báo', actual:'Thực tế', forecast:'Dự báo', revenue:'Doanh thu', purchase:'Mua hàng và chi phí trực tiếp', cost:'Giá thành sản xuất', profit:'Lợi nhuận', margin:'Tỷ suất lợi nhuận', current:'Thực tế đến hiện tại', remaining:'Dự báo còn lại', monthEnd:'Dự báo cuối tháng', compared:'So với dự toán', composition:'Cơ cấu lãi lỗ cuối tháng', order:'Đơn hàng', customer:'Khách hàng', style:'Kiểu dáng', progress:'Tiến độ', status:'Trạng thái', completed:'Hoàn thành sản xuất', producing:'Đang sản xuất', review:'Cần kiểm tra', adjustment:'Điều chỉnh lịch phân công còn lại', adjustmentHint:'Thay đổi thời gian phân công sẽ tính lại chi phí và dự báo lợi nhuận cuối tháng.', factoryUnit:'Nhà máy', quantity:'Số lượng', start:'Bắt đầu', end:'Kết thúc', impact:'Ảnh hưởng dự báo', delayed:'Chuyển sang tháng sau', within:'Hoàn thành trong tháng' },
};
const money = (v) => `${Math.round(v).toLocaleString()} ₫`;
const metrics = [
  { key:'revenue', actual:842000000, forecast:438000000 },
  { key:'purchase', actual:276000000, forecast:151000000 },
  { key:'cost', actual:332000000, forecast:188000000 },
];
const orders = [
  { order:'L16-2', customer:'THE SAN', style:'AJ1955', progress:99, status:'review', revenue:76800000, cost:61200000 },
  { order:'L16-3', customer:'THE SAN', style:'AJ2016', progress:92, status:'producing', revenue:186000000, cost:141000000 },
  { order:'TKD260602', customer:'우리둘', style:'AA2006', progress:29, status:'producing', revenue:396000000, cost:318000000 },
  { order:'E14-4', customer:'THE SAN', style:'AA1962', progress:100, status:'completed', revenue:132000000, cost:98000000 },
];
const assignments = [
  { order:'L16-3', style:'AJ2016', factory:'BARO 1', qty:200, start:'2026-08-18', end:'2026-08-24', impact:-2800000 },
  { order:'TKD260602', style:'AA2006', factory:'BARO 1', qty:3300, start:'2026-08-21', end:'2026-09-17', impact:-11400000, delayed:true },
  { order:'D50', style:'AJ2064', factory:'BARO 1', qty:180, start:'2026-08-25', end:'2026-08-29', impact:1900000 },
];
const MetricCard = ({ label, value, helper, profit }) => <Paper variant="outlined" sx={{p:2,borderRadius:2,minWidth:0}}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h6" fontWeight={800} color={profit?'success.main':'text.primary'} noWrap>{value}</Typography><Typography variant="caption" color="text.secondary">{helper}</Typography></Paper>;

const RevenueAnalysis = () => {
  const { languageCode } = useLanguage();
  const t = TEXT[languageCode] || TEXT.en;
  const [tab,setTab] = useState('monthly');
  const actualRevenue=metrics[0].actual, forecastRevenue=metrics[0].forecast;
  const actualCost=metrics[1].actual+metrics[2].actual, forecastCost=metrics[1].forecast+metrics[2].forecast;
  const actualProfit=actualRevenue-actualCost, forecastProfit=forecastRevenue-forecastCost;
  const totalRevenue=actualRevenue+forecastRevenue, totalProfit=actualProfit+forecastProfit;
  const status = { completed:{label:t.completed,color:'success'}, producing:{label:t.producing,color:'primary'}, review:{label:t.review,color:'error'} };
  return <AppPageContainer title={t.title}><Stack spacing={2}>
    <Alert severity="info">{t.demo}</Alert>
    <Paper variant="outlined" sx={{px:2,borderRadius:2}}><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" scrollButtons="auto"><Tab value="monthly" label={t.monthly}/><Tab value="orders" label={t.orders}/><Tab value="adjust" label={t.adjust}/></Tabs></Paper>
    <Stack direction={{xs:'column',sm:'row'}} spacing={1.5} justifyContent="space-between"><Stack direction="row" spacing={1} alignItems="center"><TextField size="small" type="month" label={t.month} defaultValue="2026-08" InputLabelProps={{shrink:true}}/><Chip size="small" label={t.hybrid} color="warning" variant="outlined"/></Stack><FormControl size="small" sx={{minWidth:180}}><InputLabel>{t.factory}</InputLabel><Select label={t.factory} defaultValue="all"><MenuItem value="all">{t.all}</MenuItem><MenuItem value="1">BARO 1</MenuItem><MenuItem value="2">BARO 2</MenuItem></Select></FormControl></Stack>
    {tab==='monthly'&&<>
      <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,1fr)',xl:'repeat(4,1fr)'},gap:1.5}}><MetricCard label={t.revenue} value={money(totalRevenue)} helper={`${t.actual} ${money(actualRevenue)} · ${t.forecast} ${money(forecastRevenue)}`}/><MetricCard label={t.purchase} value={money(metrics[1].actual+metrics[1].forecast)} helper={`${t.actual} + ${t.forecast}`}/><MetricCard label={t.cost} value={money(metrics[2].actual+metrics[2].forecast)} helper={`${t.actual} + ${t.forecast}`}/><MetricCard label={t.profit} value={money(totalProfit)} helper={`${t.margin} ${(totalProfit/totalRevenue*100).toFixed(1)}% · ${t.compared} +2.4%`} profit/></Box>
      <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'1.15fr .85fr'},gap:2}}><Paper variant="outlined" sx={{p:2.5,borderRadius:2}}><Stack direction="row" justifyContent="space-between" mb={2}><Typography fontWeight={700}>{t.composition}</Typography><Stack direction="row" spacing={1}><Chip size="small" label={t.actual} color="success" variant="outlined"/><Chip size="small" label={t.forecast} color="warning" variant="outlined"/></Stack></Stack><Stack spacing={2}>{metrics.map(row=>{const total=row.actual+row.forecast;return <Box key={row.key}><Stack direction="row" justifyContent="space-between"><Typography variant="body2" fontWeight={600}>{t[row.key]}</Typography><Typography variant="body2" fontWeight={700}>{money(total)}</Typography></Stack><Box sx={{height:10,bgcolor:'grey.200',borderRadius:5,overflow:'hidden',display:'flex',my:.75}}><Box sx={{width:`${row.actual/total*100}%`,bgcolor:'success.main'}}/><Box sx={{flex:1,bgcolor:'warning.main'}}/></Box><Stack direction="row" justifyContent="space-between"><Typography variant="caption">{t.actual} {money(row.actual)}</Typography><Typography variant="caption">{t.forecast} {money(row.forecast)}</Typography></Stack></Box>})}</Stack></Paper><Paper variant="outlined" sx={{p:2.5,borderRadius:2}}><Typography fontWeight={700} mb={2}>{t.monthEnd}</Typography><Stack spacing={2}><Stack direction="row" justifyContent="space-between"><Typography>{t.current}</Typography><Typography fontWeight={700}>{money(actualProfit)}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography>{t.remaining}</Typography><Typography fontWeight={700}>{money(forecastProfit)}</Typography></Stack><Stack direction="row" justifyContent="space-between" sx={{borderTop:1,borderColor:'divider',pt:2}}><Typography fontWeight={800}>{t.profit}</Typography><Typography variant="h6" color="success.main" fontWeight={800}>{money(totalProfit)}</Typography></Stack></Stack></Paper></Box>
    </>}
    {tab==='orders'&&<TableContainer component={Paper} variant="outlined" sx={{borderRadius:2}}><Table><TableHead><TableRow><TableCell>{t.order}</TableCell><TableCell>{t.customer}</TableCell><TableCell>{t.style}</TableCell><TableCell>{t.progress}</TableCell><TableCell>{t.status}</TableCell><TableCell align="right">{t.revenue}</TableCell><TableCell align="right">{t.cost}</TableCell><TableCell align="right">{t.profit}</TableCell></TableRow></TableHead><TableBody>{orders.map(row=>{const s=status[row.status];return <TableRow key={`${row.order}-${row.style}`} hover><TableCell sx={{fontWeight:700}}>{row.order}</TableCell><TableCell>{row.customer}</TableCell><TableCell>{row.style}</TableCell><TableCell sx={{minWidth:140}}><LinearProgress variant="determinate" value={row.progress} color={row.status==='review'?'error':'primary'}/><Typography variant="caption">{row.progress}%</Typography></TableCell><TableCell><Chip size="small" label={s.label} color={s.color} variant={row.status==='completed'?'filled':'outlined'}/></TableCell><TableCell align="right">{money(row.revenue)}</TableCell><TableCell align="right">{money(row.cost)}</TableCell><TableCell align="right" sx={{fontWeight:700,color:'success.main'}}>{money(row.revenue-row.cost)}</TableCell></TableRow>})}</TableBody></Table></TableContainer>}
    {tab==='adjust'&&<Stack spacing={1.5}><Paper variant="outlined" sx={{p:2.5,borderRadius:2}}><Typography fontWeight={700}>{t.adjustment}</Typography><Typography variant="body2" color="text.secondary">{t.adjustmentHint}</Typography></Paper>{assignments.map(row=><Paper key={`${row.order}-${row.style}`} variant="outlined" sx={{p:2,borderRadius:2,borderLeft:4,borderLeftColor:row.delayed?'warning.main':'success.main'}}><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1.2fr .7fr .8fr 1fr 1fr 1fr'},gap:1.5,alignItems:'center'}}><Box><Typography fontWeight={800}>{row.order} · {row.style}</Typography><Typography variant="caption">{t.factoryUnit}: {row.factory}</Typography></Box><Typography variant="body2">{t.quantity} <strong>{row.qty.toLocaleString()}</strong></Typography><Chip size="small" label={row.delayed?t.delayed:t.within} color={row.delayed?'warning':'success'} variant="outlined"/><TextField size="small" type="date" label={t.start} defaultValue={row.start} InputLabelProps={{shrink:true}}/><TextField size="small" type="date" label={t.end} defaultValue={row.end} InputLabelProps={{shrink:true}}/><Box textAlign={{md:'right'}}><Typography variant="caption">{t.impact}</Typography><Typography fontWeight={800} color={row.impact>=0?'success.main':'error.main'}>{row.impact>=0?'+':''}{money(row.impact)}</Typography></Box></Box></Paper>)}</Stack>}
  </Stack></AppPageContainer>;
};
export default RevenueAnalysis;
